[package]
name = "recursia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
ahash = "0.8.3"
#TODO: remove dynamic_linking for releases (automate this)
#TODO: add features ktx2 and zstd to enable better texture performance and compression when using ktx2 textures
#TODO: maybe enable wayland feature?
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_fly_camera = "0.10.0"
bracket-noise = "0.8.7"
dashmap = "5.4.0"
futures-lite = "1.13.0"
serde = { version = "1.0.162", features = ["derive"] }
leafwing-input-manager = "0.9.2"
bevy-inspector-egui = "0.18.3"
bevy_atmosphere = "0.6.0"

#TODO: check if parallel makes things faster once I have many physics objects
bevy_rapier3d = { version = "0.21.0", features = [ "simd-stable", "debug-render-3d", "parallel" ] }
big-brain = "0.17.0"

